name: GitHub Actions
on: 
  push:
  schedule:
    - cron: '0 0 * * 0,6' # 土曜日,日曜日の午前0時に起動
jobs:
  backend:
    name: ruby
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.1-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          apk add --no-cache alpine-sdk build-base bash
          apk add -U chromium chromium-chromedriver
      - name: bundle install
        run: |
          ruby -v
          gem install bundler:2.1.4
          bundle install
        working-directory: ${{ github.workspace }}/backend
      - name: run ruby
        run: ruby scrape.rb
        working-directory: ${{ github.workspace }}/backend
      - name: copy file
        run: cp halo.json ../frontend/my-app/utils
        working-directory: ${{ github.workspace }}/backend
      - name: git setting
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Commit files
        run: |
          git add -A
          if ! git diff-index --quiet HEAD --; then git commit -a -m "Update json (By GitHub Actions)"; fi;
          git push
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  frontend:
    name: nextapp
    needs: backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: git setting
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
      - name: install dependency
        run: yarn install
        working-directory: ${{ github.workspace }}/frontend/my-app
      - name: build React App
        run: |
          yarn run build
          touch out/.nojekyll
        working-directory: ${{ github.workspace }}/frontend/my-app
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./frontend/my-app/out
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."