name: build
on: workflow_dispatch
jobs:
  frontend:
    name: nextapp
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: git setting
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
      - name: install dependency
        run: yarn install
        working-directory: ${{ github.workspace }}/frontend
      - name: build React App
        run: |
          yarn run build
          touch out/.nojekyll
        working-directory: ${{ github.workspace }}/frontend
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./frontend/out
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."