name: Scrape 1
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5' # 金曜日の21時に起動
jobs:
  backend:
    name: ruby
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6' 
      - name: bundle install
        run: |
          gem install bundler:2.1.4
          bundle install
        working-directory: ${{ github.workspace }}/backend
      - name: run ruby
        run: |
          docker ps
          ruby scrape.rb
        working-directory: ${{ github.workspace }}/backend
      - name: copy file
        run: cp halo.json ../frontend/utils
        working-directory: ${{ github.workspace }}/backend
      - name: git setting
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Commit files
        run: |
          git add -A
          if ! git diff-index --quiet HEAD --; then git commit -a -m "Update json (By GitHub Actions)"; fi;
          git push
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  frontend:
    name: nextapp
    needs: backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: git setting
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
      - name: install dependency
        run: yarn install
        working-directory: ${{ github.workspace }}/frontend
      - name: build React App
        run: |
          yarn run build
          touch out/.nojekyll
        working-directory: ${{ github.workspace }}/frontend
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./frontend/out
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."