name: GitHub Actions Test
on: 
  schedule:
    - cron: '0 12 * * 0,5,6' # 金,土曜日の21時に起動
jobs:
  backend:
    name: ruby
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was test event."